spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.248.138:3306/friday?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      test-while-idle: true
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


  jpa:
    show-sql: true

    properties:
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true

  redis:
    host: 192.168.248.138
    port: 6379
    password:
    timeout: 10s

    lettuce:

      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  sql:
    init:
      platform: mysql

token:
  header: Authorization
  secret: (FRIDAY:)_$^11244^%$_(IS:)_@@++--(COOL:)_++++_.sds_(GUY:)
  expireTime: 60












